# Generated by Django 5.1.4 on 2024-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='Is Instructor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='Is Student'),
        ),
    ]
