# Generated by Django 5.1.5 on 2025-01-29 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_delete_userprofile'),
        ('users', '0003_alter_customuser_is_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('status_image', models.ImageField(blank=True, null=True, upload_to='status/')),
                ('completed_courses', models.ManyToManyField(blank=True, to='courses.course')),
                ('interests', models.ManyToManyField(blank=True, to='users.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
