# Generated by Django 5.1.4 on 2024-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
