# Generated by Django 5.1.4 on 2024-12-30 16:19

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.discussionreply'),
        ),
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='courses.discussionthread'),
        ),
    ]
