# Generated by Django 5.1.4 on 2024-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_notification_reply_notification_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_image',
            field=models.ImageField(blank=True, null=True, upload_to='status/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
