# Generated by Django 5.1.4 on 2024-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_message_parent_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
