# Generated by Django 5.1.5 on 2025-01-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
